baseURL = 'https://kaniyam.ca/'
languageCode = 'en-us'
title = "Kaniyam Foundation"
Paginate = 4
PaginatePath = "/"
summaryLength = 10

[taxonomies]
category = "categories"

[permalinks]
posts = ":section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
unsafe = true

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'